# Site settings
title: ClojureBridge Curriculum
email: info@clojurebridge.org
baseurl: /curriculum
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://clojurebridge.github.io/"
twitter_username: ClojureBridge
github_username:  ClojureBridge

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true
encoding: UTF-8
exclude:
- Gemfile
- Gemfile.lock
- CONTRIBUTING.md
- EDITING-CURRICULUM.md
- ClojurebridgeCheatsheet-v2.pdf
- TEACHING.md
- background-reading.md
- tmp

# Port number
port: 5555

